all:
	g++ main.cpp mesh.cpp TextureManager.cpp shader.cpp controls.cpp objloader.cpp tangentspace.cpp vboindexer.cpp -o main -Wall -lglfw3 -lm -lGL -lGLU -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lGLEW -lrt -lfreeimage

